### ISSUE TITLE
luctus-discord

### ISSUE THREAD

**Issue by ege75753** [OverlordAkise/darkrp-addons#6]
[luctus_discord] Couldn't connect to server
  
1 - unknown - addons/luctus_discord/lua/autorun/server/sv_luctus_discord_config.lua:26

i have been stuck with this on my darkrp server any ideas on how to fix it ?

**Comment by OverlordAkise** [comment]
I tried to explain it in the README:

Garry's Mod servers are by default not allowed to send discord messages. That's why you need either a custom .dll file or a proxy, my addon uses a proxy to do this.

You either need to run your own on your linux server or you can use mine.
If you want to use mine please contact me (discord "overlordakise")

I don't let everyone use mine by default because people could spam me and my IP would get blacklisted by discord, that's why people have to ask me for it first, sorry for the inconvenience.
